### ISSUE TITLE
Upgrade to Solidity ^0.8.0

### ISSUE THREAD

**Issue by mikeghen** [Ricochet-Exchange/rex-bank#22]
Go through and upgrade the contracts to version 0.8.0

**Comment by josealonso** [comment]
I take this issue before migrating to hardhat.

**Comment by josealonso** [comment]
I think this issue is now fixed, although I only typed *truffle compile* to make sure there are no errors.

**Comment by mikeghen** [comment]
Nice work again, thanks you @josealonso

**Comment by josealonso** [comment]
Glad you liked it, @mikeghen. I'm gonna write down what you told me about the Ownable function. I understand that the Open Zeppelin's Ownable shouldn't be used. I read it on my cell phone, but I don't remember where you posted it. Could you clarify that ? No need to hurry up, I'm gonna switch to the hardhat deployment issue.
